module GoldyLox
  class AstPrinter
    include _ExpressionVisitor[String]
    include _StatementVisitor[String]

    def print: (Statement | Expression) -> String

    def parenthesize: (_ToS, *Expression) -> String
  end
end
