module GoldyLox
  class AstPrinter[String]
    include _ExpressionVisitor[String]
    include _StatementVisitor[String]

    def print: (Statement | Expression) -> String

    def parenthesize: (String, *Expression) -> String
  end
end
