module GoldyLox
  class Environment
    class UndefinedVariableError < RuntimeError
      attr_reader name: Token

      def initialize: (String message, Token name) -> void
    end

    private attr_reader enclosing: instance
    private attr_reader values: Hash[String, untyped]

    @enclosing: instance?
    @values: Hash[String, untyped]

    def initialize: (?instance? enclosing) -> void

    def define: (String name, untyped value) -> void

    def get: (Token name) -> untyped
    def get_at: (Integer distance, String name) -> untyped

    def assign: (Token name, untyped value) -> void
    def assign_at: (Integer distance, Token name, untyped value) -> void

    private

    def ancestor: (Integer distance) -> instance
  end
end
