module GoldyLox
  class Environment
    class UndefinedVariableError < RuntimeError
      attr_reader name: Token

      def initialize: (String message, Token name) -> void
    end

    @enclosing: instance?
    @values: Hash[String, untyped]

    def initialize: (?instance? enclosing) -> void

    def define: (String name, untyped value) -> void

    def get: (Token name) -> untyped

    def assign: (Token name, untyped value) -> void

    private

    def assert_defined: (Token name) -> void
  end
end
