# frozen_string_literal: true

module GoldyLox
  class LoxFunction
    include _Callable

    @declaration: Statement::Function
    @closure: Environment
    @block: Proc

    def initialize: (Statement::Function declaration, Environment closure) -> void
  end

  class NativeFunction
    include _Callable

    @arity: Integer
    @block: Proc

    def initialize: (Integer arity) { () -> untyped } -> void
  end
end
