# frozen_string_literal: true

module GoldyLox
  class LoxFunction
    include _Callable

    @declaration: Statement::Function
    @closure: Environment
    @is_initializer: bool

    def initialize: (Statement::Function declaration, Environment closure, bool is_initializer) -> void

    def bind: (LoxInstance) -> instance
  end

  class NativeFunction
    include _Callable

    @arity: Integer
    @block: Proc

    def initialize: (Integer arity) { () -> untyped } -> void
  end
end
