module GoldyLox
  class Interpreter
    class InvalidOperandError < RuntimeError
      attr_reader operator: Token
      attr_reader value: untyped

      def initialize: (Token operator, untyped value) -> void
    end

    include _ExpressionVisitor[void]
    include _StatementVisitor[void]

    @out: _Appendable

    def initialize: (_Appendable) -> void

    def interpret: (Array[Statement]) -> void
    def execute: (Statement) -> void
    def evaluate: (Expression) -> untyped

    def assert_numeric_operands: (Token operator, *untyped operands) -> void
  end
end
