module GoldyLox
  class Interpreter
    class InvalidOperandError < RuntimeError
      attr_reader operator: Token
      attr_reader value: untyped

      def initialize: (Token operator, untyped value) -> void
    end

    class Return < RuntimeError
      attr_reader value: untyped

      def initialize: (untyped value) -> void
    end

    include _ExpressionVisitor[void]
    include _StatementVisitor[void]
    include Resolver::_Resolvable

    @out: _Appendable
    @globals: Environment
    @environment: Environment
    @locals: Hash[Expression, Integer]

    def initialize: (_Appendable) -> void

    def interpret: (Array[Statement]) -> void
    def execute: (Statement) -> void
    def execute_block: (Statement::Block, Environment) -> void
    def evaluate: (Expression) -> untyped

    private

    def assert_numeric_operands: (Token operator, *untyped operands) -> void

    def lookup_variable: (Token name, Expression expr) -> untyped
  end
end
