module GoldyLox
  class LoxClass
    include _Callable

    attr_reader name: String

    @methods: Hash[String, LoxFunction]

    def initialize: (String name, Hash[String, LoxFunction] methods) -> void

    def find_method: (String) -> LoxFunction?
  end
end
