module GoldyLox
  class Parser
    include Grammar
    include TokenUtilities

    @tokens: Array[Token]
    @current: Integer

    attr_reader errors: Array[ParseError]

    def initialize: (Array[Token]) -> void

    # @raise ParseError
    def parse: -> Array[Statement]

    def error: (Token, String) -> void
    def synchronize: -> void
  end
end
