module GoldyLox
  class Runner
    @out: _Appendable
    @err: _Appendable
    @printer: AstPrinter
    @interpreter: Interpreter

    def initialize: (?_Appendable out, ?_Appendable err) -> void

    def run: (String) -> void

    def log_error: (String, Integer) -> void
    def log_result: (_ToS) -> void

    def single_expression?: (Array[Statement]) -> bool
  end
end
