# frozen_string_literal: true

module GoldyLox
  class Scanner
    class LexicalError < StandardError
      attr_reader line: Numeric

      def initialize: (String, Numeric) -> void
    end

    attr_reader errors: Array[LexicalError]

    @source: String
    @start: Integer
    @current: Integer
    @line: Integer
    @tokens: Array[Token]

    def initialize: (String) -> void

    def scan_tokens: () -> Array[Token]

    def eof?: () -> bool

    def scan_token: () -> void

    def string: () -> void

    def match: (String) -> bool

    def peek: () -> String

    def advance: () -> String

    def add_token: (Symbol, ?(nil | Numeric | String)) -> void
  end
end