module GoldyLox
  class Statement
    def accept: [R] (_StatementVisitor[R]) -> R

    def self.attrs: (*Symbol) -> void

    class Block < Statement
      attr_reader statements: Array[Statement]

      def initialize: (Array[Statement] statements) -> void
    end

    class Expression < Statement
      attr_reader expression: GoldyLox::Expression

      def initialize: (GoldyLox::Expression expression) -> void
    end

    class If < Statement
      attr_reader condition: GoldyLox::Expression
      attr_reader then_branch: Statement
      attr_reader else_branch: Statement?

      def initialize: (GoldyLox::Expression condition, Statement then_branch, Statement? else_branch) -> void
    end

    class Print < Statement
      attr_reader expression: GoldyLox::Expression

      def initialize: (GoldyLox::Expression expression) -> void
    end

    class Var
      attr_reader name: Token
      attr_reader initializer: GoldyLox::Expression?

      def initialize: (Token name, GoldyLox::Expression? initializer) -> void
    end
  end
end
