module GoldyLox
  class Token
    TYPES: Array[Symbol]

    attr_reader type: Symbol
    attr_reader line: Integer
    attr_reader lexeme: String
    attr_reader literal: nil | Numeric | String

    def initialize: (Symbol type, Integer line, String lexeme, ?nil | Numeric | String literal) -> void

    def to_s: -> String
  end
end