AllCops:
  TargetRubyVersion: 3.4
  NewCops: disable

# A couple of rules to make this more like Rails omakase
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/LineLength:
  Max: 120

Lint/BooleanSymbol:
  Enabled: false

Metrics:
  Enabled: false